version: '3.8'

services:
  app:
    build: ""
    container_name: 'akka-phone'
    ports:
      - '18080:8080'
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/akka_phone?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=akka_phone
      - SPRING_DATASOURCE_PASSWORD=letmein
      - SPRING_PROFILES_ACTIVE=local
    networks:
      - akka-phone

  db:
    image: postgres
    container_name: 'postgres'
    ports:
      - '15432:5432'
    environment:
      - POSTGRES_USER=akka_phone
      - POSTGRES_PASSWORD=letmein
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U akka_phone"]
      interval: 2s
      timeout: 3s
      retries: 15
    volumes:
      - ./_db:/var/lib/postgresql/data
    networks:
      - akka-phone

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - ./_rabbitmq-data:/var/lib/rabbitmq/
      - ./_rabbitmq-data:/var/log/rabbitmq
    networks:
      - akka-phone

  redis:
    image: redis:alpine
    container_name: 'redis'
    ports:
      - 16379:6379
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli", "ping"]
      interval: 2s
      timeout: 3s
      retries: 15
    volumes:
      - ./_redis:/data
    networks:
      - akka-phone

networks:
  akka-phone:


