global:
  scrape_interval: 2s
  scrape_timeout: 2s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: 'Akka Phone App'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 2s
    static_configs:
      - targets:
          - 'host.docker.internal:8080'
        labels:
          application: 'akka-phone'